name: Python Test & CI/CD

on:
  push:
    branches: [main]
    paths-ignore:
    - 'ansible/**'
    - 'terraform/**'
    - 'kubernetes/**'
    - 'monitoring/**'
    - README.md

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirments.txt

    - name: Run tests
      run: python -m pytest

  build-and-push-docker:
    name: GitHub Actions CI
    runs-on: ubuntu-latest
    needs: test

    env:
      REPOSITORY: dockerized_project # Define Dockerhub repo here
      IMAGE_TAG: v0.1 # Define the image tag here

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .

    - name: Push Docker image
      run: docker push "${{ secrets.DOCKER_USERNAME }}"/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}



